import mongoose from "mongoose";
import { List } from "../models/list.model";
import { Todo } from "../models/todo.model";
import { ApiError } from "../utils/ApiError";
import { ApiResponse } from "../utils/ApiResponse";
import { asyncHandler } from "../utils/asyncHandler";
import { stringValidator } from "../utils/typeValidation";

const createList = asyncHandler(async (req, res) => {
  const { name } = req.body;

  if (!name) {
    throw new ApiError(400, "Name is required");
  }

  if (!stringValidator.safeParse(name).success) {
    throw new ApiError(400, "Invalid Type: Name must be a string");
  }

  //checks if list exists already with the name
  const existingList = await List.findOne({
    name,
    owner: req.user._id,
  });

  //throws error if list with the name already exists
  if (existingList) {
    throw new ApiError(400, "List already exists");
  }

  const list = await List.create({
    name,
    owner: req.user._id,
  });

  if (!list) {
    throw new ApiError(500, "Something went wrong while creating the list");
  }

  //returns the created list
  return res
    .status(200)
    .json(new ApiResponse(200, list, "List created successfully"));
});

const deleteList = asyncHandler(async (req, res) => {
  const { listId } = req.params;

  if (!listId) {
    throw new ApiError(400, "Invalid List ID");
  }

  const list = (await List.findOne({
    _id: listId,
  })) as any;

  if (!list) {
    throw new ApiError(400, "List doesn't exist");
  }

  //validates if the owner of list and the logged in user are the same or not
  if (!list.owner._id.equals(req.user._id)) {
    throw new ApiError(401, "Unauthorized Request");
  }

  //checks if the list is protected or not
  //protected are the ones that are generated by default like Inbox
  if (list.protected == true) {
    throw new ApiError(400, "This list cannot be deleted");
  }

  const deletedList = await List.deleteOne({
    _id: listId,
  });

  if (!deletedList) {
    throw new ApiError(500, "Something went wrong while deleting the list");
  }

  //delets all the uncompleted todos of the list
  await Todo.deleteMany({
    list: new mongoose.Types.ObjectId(listId),
    isDone: false,
  });

  return res
    .status(200)
    .json(new ApiResponse(200, {}, "List deleted successfully"));
});

const updateList = asyncHandler(async (req, res) => {
  const { listId } = req.params;
  const { name } = req.body;

  if (!listId) {
    throw new ApiError(400, "Invalid List ID");
  }

  const list = (await List.findById(listId)) as any;

  if (!list) {
    throw new ApiError(400, "List doesn't exist");
  }

  if (!name) {
    throw new ApiError(400, "Name is required to update");
  }

  if (!stringValidator.safeParse(name).success) {
    throw new ApiError(400, "Invalid Type: Name must be a string");
  }

  //validates if the owner of list and the logged in user are the same or not
  if (!list.owner._id.equals(req.user._id)) {
    throw new ApiError(401, "Unauthorized Request");
  }

  //checks if list is protected
  if (list.protected == true) {
    throw new ApiError(400, "This list cannot be modified");
  }

  //checks if list with the updated name exists already
  const existingName = await List.findOne({
    name,
    owner: req.user._id,
  });

  if (existingName) {
    throw new ApiError(
      400,
      "A list with the name already exists in your account",
    );
  }

  list.name = name;

  await list.save({ validateBeforeSave: false });

  return res
    .status(200)
    .json(new ApiResponse(200, list, "List updated successfully"));
});

const getList = asyncHandler(async (req, res) => {
  const { listId } = req.params;

  if (!listId) {
    throw new ApiError(400, "Invalid List ID");
  }

  const list = (await List.findById(listId)) as any;

  if (!list) {
    throw new ApiError(400, "Something went wrong while fetching the list");
  }

  if (!list.owner._id.equals(req.user._id)) {
    throw new ApiError(401, "Unauthorized Request");
  }

  return res
    .status(200)
    .json(new ApiResponse(200, list, `${list.name} fetched successfully`));
});

const addTodoToList = asyncHandler(async (req, res) => {
  const { todoId } = req.query;
  const { listId } = req.params;

  const errors = [];

  if (!listId) {
    errors.push("Invalid List ID");
  }

  if (!todoId) {
    errors.push("Invalid Todo ID");
  }

  if (errors.length > 0) {
    throw new ApiError(400, errors.join("; "));
  }

  const list = (await List.findById(listId)) as any;

  if (!list) {
    throw new ApiError(400, "Something went wrong while fetching the list");
  }

  //validates if the owner of list and the logged in user are the same or not
  if (!list.owner._id.equals(req.user._id)) {
    throw new ApiError(401, "Unauthorized Request");
  }

  const todo = await Todo.findById(todoId);

  // checks if the todo exists or not
  if (!todo) {
    throw new ApiError(400, "Something went wrong while looking for the todo");
  }

  todo.list = list._id;

  await todo.save({ validateBeforeSave: false });

  return res
    .status(200)
    .json(
      new ApiResponse(
        200,
        { todo, list },
        `Todo successfully added to the list: ${list.name}`,
      ),
    );
});

const removeTodoFromList = asyncHandler(async (req, res) => {
  const { todoId } = req.query;
  const { listId } = req.params;

  const errors = [];

  if (!listId) {
    errors.push("Invalid List ID");
  }

  if (!todoId) {
    errors.push("Invalid Todo ID");
  }

  if (errors.length > 0) {
    throw new ApiError(400, errors.join("; "));
  }

  const list = await List.findById(listId);

  if (!list) {
    throw new ApiError(400, "Something went wrong while fetching the list");
  }

  const todo = await Todo.findById(todoId);

  if (!todo) {
    throw new ApiError(400, "Something went wrong while looking for the todo");
  }

  const inbox = (await List.findOne({
    name: "Inbox",
    owner: req.user._id,
  })) as any;

  todo.list = inbox._id;

  await todo.save({ validateBeforeSave: false });

  return res
    .status(200)
    .json(
      new ApiResponse(
        200,
        { list, todo },
        `Todo successfully removed from the list: ${list.name} and added back to: ${inbox.name}`,
      ),
    );
});

const getTodosByList = asyncHandler(async (req, res) => {
  const { listId } = req.params;
  const { sortType, sortBy: sortByQuery, page = 1, limit = 10 } = req.query;

  const sortBy = (sortByQuery as string) || "createdAt";

  const userList = (await List.findById(listId)) as any;

  const sortStage = sortType == "asc" ? 1 : -1;

  if (!userList.owner.equals(req.user._id)) {
    throw new ApiError(401, "Unauthorized Request");
  }

  const listTodos = await Todo.aggregate([
    {
      $match: {
        list: new mongoose.Types.ObjectId(listId),
        isDone: false,
      },
    },
    {
      $lookup: {
        from: "lists",
        localField: "list",
        foreignField: "_id",
        as: "userList",
      },
    },
    {
      $unwind: "$userList",
    },

    {
      $sort: {
        [sortBy]: sortStage,
      },
    },
    {
      $skip: (Number(page) - 1) * Number(limit),
    },
    {
      $limit: Number(limit),
    },
    {
      $project: {
        title: 1,
        description: 1,
        dueDate: 1,
        createdAt: 1,
        listName: "$userList.name",
      },
    },
  ]);

  if (!listTodos) {
    throw new ApiError(400, "Something went wrong while looking for todos");
  }

  return res.status(200).json(
    new ApiResponse(
      200,
      {
        listTodos,
      },
      `All the Todos fetched successfully from the list: ${userList.name}`,
    ),
  );
});

const getAllLists = asyncHandler(async (req, res) => {
  const userLists = await List.aggregate([
    {
      $match: {
        owner: req.user._id,
      },
    },
    {
      $project: {
        name: 1,
        protected: 1,
      },
    },
  ]);

  return res
    .status(200)
    .json(new ApiResponse(200, userLists, "Lists fetched successfully"));
});

export {
  createList,
  deleteList,
  updateList,
  getList,
  addTodoToList,
  removeTodoFromList,
  getTodosByList,
  getAllLists,
};
